rootUrl: http://application:8000
gridUrl: http://localhost:4444/wd/hub

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome
system:
  projectRoot: .
  diffColor: '#ff0000'
  coverage:
    enabled: true
